// * * * *
// * * * *
// * * * *
// * * * *
// #include <iostream>
// using namespace std;
// int main()
// { int i,j;
//     for (i=0 ; i<4 ; i++)
 
//   {  for (j=0 ; j<4 ; j++)
//  { cout<< " *" ;}
// cout<<endl;}
// return 0;}



// # include <iostream>
// using namespace std;
// void print1(int n )
// {
//   for (int i=0; i<n; i++)
//   { 
//     for (int j=0 ; j<n ; j++)
//     { cout<<" * ";}
//     cout<<endl;

//   }
// }
// int main(){
// { int n ;
// cin>> n;}
// print1 ( n);}

// *
// * *
// * * *
// * * * *
// #include <iostream>
// using namespace std;
// void print1(int n )
// {
//   for (int i = 1 ; i<=n+1; i++)
//   { for (int j=1 ; j<=i ; j++)
//   { cout<<"*";}
//    cout<<endl;}}
// int main ()
// { int n ;
// cin>>n;
// print1(n);
// }

// 1
// 1 2
// 1 2 3
// 1 2 3 4 
// # include <iostream>                           errrrrrroooooorrrrrrrr
// using namespace std;
// void print3 (int n )
// { for (int i = 1 ; i<=n ; i++)
// {
//   for (int j = 1 ; j<=i ; j++)
//   { cout<< j;}
//   cout<<endl;
// }}
// { for (int i=1  ; i<=n ; i++)
//  for(int j =1 ; j<=i ; j++)
// }
// int main ()
// { int n ;
// cin>>n;
// print3 (n);}

#include <iostream>
using namespace std;
 int main()
{ int i,j;
    for (i=0 ; i<4 ; i++)
 
  {  for (j=0 ; j<4 ; j++)
 { cout<< " *" ;}
cout<<endl;}
return 0;}